name: ts-web-backend
services:
  backend:
    build:
      context: ../
      dockerfile: ./local/Dockerfile
    env_file: .env
    volumes:
      - ../:/home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    image: postgres:15.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ts_web_backend_dev
      POSTGRES_TEST_DB: ts_web_backend_test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    ports:
      - "5438:5432"
    expose:
      - "5432"

volumes:
  pgdata: {}
