# fly.toml app configuration file generated for ts-web-backend-staging on 2025-02-28T10:10:19-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ts-web-backend-staging'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = "1gb"

[deploy]
  release_command = "npx prisma migrate deploy"
