# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy

on:
  push:
    branches:
      - main
      - build/setup-ci-cd

jobs:
  ##
  # CI Steps
  ##
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ts_web_backend_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d ts_web_backend_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: test
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/ts_web_backend_test'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run database migrations
        run: npm run db:migrate

      - name: Run Jest tests
        run: npx jest --coverage -c 'src/tests/jest.config.js'

  ##
  # CD Steps
  ##
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: test
    concurrency: deploy-group

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
